let ApiUrl = {
  orderMessage: "/technician/front/orderMessage.htm",
  findOrderList: "/technician/front/findOrderList.htm",
  findOrderBasicInfo: "/order/front/findOrderBasicInfo.htm",
  updateOrderStatus: "/technician/front/updateOrderStatus.htm",
  mobileCheck: "/technician/front/mobileCheck.htm",
  getVerifyCode: "/technician/front/getVerifyCode.htm",
  checkCenter: "/technician/front/checkCenter.htm",
  postCheck: "/technician/front/postCheck.htm",
  findOrderRecordDetail: "/order/front/findOrderRecordDetail.htm",
  signTechnician: "/technician/front/signTechnician.htm",
  personalCenter: "/technician/front/personalCenter.htm",
  updateTechnicianCoord: "/technician/front/updateCoord.htm",
  actionState: "/technician/front/actionState.htm",
  updateCoord: "/technician/front/updateCoord.htm",
  updateSkillType: "/technician/front/updateSkillType.htm",
  getJsapiTicket: "/other/front/getJsapiTicket.htm",
  updateOrderPrice: "/order/front/updateOrderPrice.htm",
  findCustomerInfoId: "/customer/front/findCustomerInfoId.htm",
  findCustomerInfo: "/technician/front/findCustomerInfo.htm",
  addCorrelationTechnician: "/customer/front/addCorrelationTechnician.htm",
  findPayBilldetails: "/technician/front/findPayBilldetails.htm",
  findPayBillInfo: "/pay/front/findPayBillInfo.htm",
  addUserLoginInfo: "/userLogin/front/addUserLoginInfo.htm",
  getOpenid: "/wxPay/front/getOpenid.htm",
  myInfo: "/technician/front/myInfo.htm",
  technicianInfo: "/technician/front/myInfo.htm",
  customerInfo: "/customer/front/myInfo.htm",
  findServeInfo: "/quoteServe/front/findServeInfo.htm",
  findServeDetails: "/quoteServe/front/findServeDetails.htm",
  findDeviceTypeBasics: "/quoteServe/front/findDeviceTypeBasics.htm",
  findBrandBasics: "/quoteServe/front/findBrandBasics.htm",
  findPartsInfo: "/quoteParts/front/findPartsInfo.htm",
  findPartsDetails: "/quoteParts/front/findPartsDetails.htm",
  inviteCodeCreate: "/technician/front/inviteCodeCreate.htm",
  saveTechnicianAddress: "/technician/front/saveTechnicianAddress.htm",
  findWorkOrders: "/technician/front/findWorkOrders.htm",
  findWorkOrderDetails: "/technician/front/findWorkOrderDetails.htm",
  addWorkOrder: "/technician/front/addWorkOrder.htm",
  updateWorkOrder: "/technician/front/updateWorkOrder.htm",
  findIndentureCust: "/technician/front/findIndentureCust.htm",
  uploadFile: "/other/front/uploadFile.htm",
};
export default ApiUrl;




// let ApiUrl = {
//   orderMessage: "/mock/orderMessage.json",
//   findOrderBasicInfo: "/mock/findOrderBasicInfo.json",
//   updateOrderStatus: "/mock/updateOrderStatus.json",
//   mobileCheck: "/mock/mobileCheck.json",
//   getVerifyCode: "/mock/getVerifyCode.json",
//   checkCenter: "/mock/checkCenter.json",
//   postCheck: "/mock/postCheck.json",
//   findOrderRecordDetail: "/mock/findOrderRecordDetail.json",
//   signTechnician: "/mock/signTechnician.json",
//   personalCenter: "/mock/personalCenter.json",
//   updateTechnicianCoord: "/mock/updateCoord.json",
//   actionState: "/mock/actionState.json",
//   updateCoord: "/mock/updateCoord.json",
//   updateSkillType: "/mock/updateSkillType.json",
//   getJsapiTicket: "/mock/getJsapiTicket.json",
//   updateOrderPrice: "/mock/updateOrderPrice.json",
//   findCustomerInfoId: "/mock/findCustomerInfoId.json",
//   findCustomerInfo: "/mock/findCustomerInfo.json",
//   addCorrelationTechnician: "/mock/addCorrelationTechnician.json",
//   findPayBilldetails: "/mock/findPayBilldetails.json",
//   findPayBillInfo: "/mock/findPayBillInfo.json",
//   addUserLoginInfo: "/mock/addUserLoginInfo.json",
//   getOpenid: "/mock/getOpenid.json",
//   myInfo: "/mock/myInfo.json",
//   findServeInfo: "/mock/findServeInfo.json",
//   findServeDetails: "/mock/findServeDetails.json",
//   findDeviceTypeBasics: "/mock/findDeviceTypeBasics.json",
//   findBrandBasics: "/mock/findBrandBasics.json",
//   findPartsInfo: "/mock/findPartsInfo.json",
//   findPartsDetails: "/mock/findPartsDetails.json",
//   inviteCodeCreate: "/mock/inviteCodeCreate.json",
//   saveTechnicianAddress: "/mock/saveTechnicianAddress.json",
//   findWorkOrders: "/mock/findWorkOrders.json",
//   findWorkOrderDetails: "/mock/findWorkOrderDetails.json",
//   addWorkOrder: "/mock/addWorkOrder.json",
//   updateWorkOrder: "/mock/updateWorkOrder.json",
//   findIndentureCust: "/mock/findIndentureCust.json",
//   uploadFile: "/mock/uploadFile.json",
//   findOrderList: "/mock/findOrderList.json"
// };
// export default ApiUrl;


